kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
data:
  nginx.conf: "# For more information on configuration, see:\n#   * Official English Documentation: http://nginx.org/en/docs/\n#   * Official Russian Documentation: http://nginx.org/ru/docs/\n\n\nworker_processes auto;\nerror_log /var/log/nginx/error.log;\npid /run/nginx.pid;\n\n# Load dynamic modules. See /usr/share/doc/nginx/README.dynamic.\ninclude /usr/share/nginx/modules/*.conf;\n\nevents {\n    worker_connections 1024;\n}\n\nhttp {\n    # perl_modules /opt/app-root/etc/perl;\n    # perl_require Version.pm;\n    # perl_set $perl_version Version::installed;\n\n    log_format  main  '$remote_addr - $remote_user [$time_local] \"$request\" '\n                      '$status $body_bytes_sent \"$http_referer\" '\n                      '\"$http_user_agent\" \"$http_x_forwarded_for\"';\n\n\n    sendfile            on;\n    tcp_nopush          on;\n    tcp_nodelay         on;\n    keepalive_timeout   65;\n    types_hash_max_size 2048;\n\n    include             /etc/nginx/mime.types;\n    default_type        application/octet-stream;\n\n    # Load modular configuration files from the /etc/nginx/conf.d directory.\n    # See http://nginx.org/en/docs/ngx_core_module.html#include\n    # for more information.\n    include /opt/app-root/etc/nginx.d/*.conf;\n\n    server {\n        listen       8080 default_server;\n        listen       [::]:8080 default_server;\n        server_name  _;\n        root         /opt/app-root/src;\n\n        # Load configuration files for the default server block.\n        include /opt/app-root/etc/nginx.default.d/*.conf;\n\n\tlocation / {\n        }\n\n        error_page 404 /404.html;\n            location = /40x.html {\n        }\n\n        error_page 500 502 503 504 /50x.html;\n            location = /50x.html {\n        }\n    }\n\n# Settings for a TLS enabled server.\n#\n#    server {\n#        listen       443 ssl http2 default_server;\n#        listen       [::]:443 ssl http2 default_server;\n#        server_name  _;\n#        root         /opt/app-root/src;\n#\n#        ssl_certificate \"/etc/pki/nginx/server.crt\";\n#        ssl_certificate_key \"/etc/pki/nginx/private/server.key\";\n#        ssl_session_cache shared:SSL:1m;\n#        ssl_session_timeout  10m;\n#        ssl_ciphers PROFILE=SYSTEM;\n#        ssl_prefer_server_ciphers on;\n#\n#        # Load configuration files for the default server block.\n#        include /opt/app-root/etc/nginx.default.d/*.conf;\n#\n#        location / {\n#        }\n#\n#        error_page 404 /404.html;\n#            location = /40x.html {\n#        }\n#\n#        error_page 500 502 503 504 /50x.html;\n#            location = /50x.html {\n#        }\n#    }\n\n}\n\n"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-img-config
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: web-img-config
spec:
  selector:
    app: web-img-config
  ports:
    - port: 8080
      protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-img-config
  labels:
    app: web-img-config
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-img-config
  template:
    metadata:
      labels:
        app: web-img-config
    spec:
      containers:
        - name: web-img-config
          image: danieldocke/web-img-configmap:1.0
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: storage
              mountPath: /opt/app-root/src/provider
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: web-img-config
        - name: nginx-config
          configMap:
            name: nginx-config
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: web-img-config
spec:
  host: web-img-config.primer-test.apps-crc.testing
  #host: lala.192.168.130.11.nip.io
  to:
    kind: Service
    name: web-img-config
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None
